version: '3'

services:
  db:
    restart: always
    image: mariadb:latest
    environment:
      MARIADB_DATABASE: cloudstorage
      MARIADB_PASSWORD: root
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: root
    ports:
      - '3306'
  minio:
    restart: always
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000'
    command: server /data
  redis:
    image: 'redis:latest'
    ports:
      - '6379'