version: '3'

services:
  db:
    restart: always
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=cloudstorage'
      - 'MARIADB_PASSWORD=root'
      - 'MARIADB_ROOT_PASSWORD=root'
      - 'MARIADB_USER=root'
    ports:
      - '3306'