version: '3.4'

services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_DATABASE: cloudstorage
      MARIADB_ROOT_PASSWORD: qRzuu2S4JON9BEfz5nAdMt58
      MARIADB_USER: root
      volumes:
        db_data:/var/lib/mysql
    ports:
      - '3306'
    healthcheck:
      test: healthcheck.sh --connect --innodb_initialized
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: 9QOYduVpm5CI5G5UV15sjAAb
    volumes:
      - minio_data:/data
    ports:
      - '9000'
    command: server /data
    healthcheck:
      test: curl -I http://minio:9000/minio/health/live
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: 'redis:latest'
    volumes:
      - redis_data:/data
    ports:
      - '6379'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    restart: unless-stopped
    image: tonkoshkur/cloud-storage:1.0.0
    environment:
      DB_URL: jdbc:mariadb://db:3306/cloudstorage
      DB_USER: root
      DB_PASSWORD: qRzuu2S4JON9BEfz5nAdMt58
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_ACCESS_SECRET: 9QOYduVpm5CI5G5UV15sjAAb
      MINIO_BUCKET_NAME: user-files
      MINIO_USER_FOLDER_FORMAT: user-%s-files/
      MINIO_INVALID_CHARACTER_REGEX: '.*[\\^*|\\\\/&\";].*'
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MAX_MULTIPART_FILE_SIZE: 10MB
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy