version: '3'

services:
  db:
    restart: always
    image: mariadb:latest
    environment:
      MARIADB_DATABASE: cloudstorage
      MARIADB_PASSWORD: root
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: root
      volumes:
        db_data:/var/lib/mysql
    ports:
      - '3306'
  minio:
    restart: always
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    ports:
      - '9000'
    command: server /data
  redis:
    image: 'redis:latest'
    volumes:
      - redis_data:/data
    ports:
      - '6379'
  app:
    restart: always
    build: ./
    ports:
      - '8080:8080'
    depends_on:
      - db
      - minio
      - redis
volumes:
  db_data:
  minio_data:
  redis_data: