spring:
  application:
    name: cloud-storage
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: ${MAX_MULTIPART_FILE_SIZE}
      max-request-size: ${MAX_MULTIPART_FILE_SIZE}
server:
  tomcat:
    max-swallow-size: -1
minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  access-secret: ${MINIO_ACCESS_SECRET}
  bucket-name: ${MINIO_BUCKET_NAME}
  user-folder-format: ${MINIO_USER_FOLDER_FORMAT}
  invalid-character-regex: ${MINIO_INVALID_CHARACTER_REGEX}