spring:
  application:
    name: cloud-storage
  datasource:
    url: jdbc:mariadb://db:3306/cloudstorage
    username: root
    password: root
  data:
    redis:
      host: redis
      port: 6379
minio:
  url: http://minio:9000
  access-key: minioadmin
  access-secret: minioadmin
  bucket-name: user-files
  user-folder-format: user-%s-files/
validation:
  name-regex: ^[a-zA-Z0-9-_.\'А-Яа-яҐЄІЇєії]+$